# Generated by Django 4.0.1 on 2022-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameentry_user_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='service',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
