# Generated by Django 4.0.1 on 2022-04-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameentry_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
